logging:
  file: ${user.home}/logs/pigutu/pigutu.log
  level.*: INFO

server:
  context-path: /
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/me?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: Xuxinwei1234.

mybatis:
  configuration:
    map-underscore-to-camel-case: true

pigutu:
  url: https://www.pigutu.com:8080/
  murl: https://m.pitutu.com/
